import { Box } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NewsRow from "../src/NewsRow";

export default function Home({ news }) {
  console.log(news);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {news.map((e) => (
        <NewsRow key= {e.time}{...e} />
      ))}
      <Link href={'test'}>test</Link>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://inshorts.deta.dev/news?category=all");
  const news = await res.json();
  console.log(`rerander===>${new Date()}`);
  return {
    props: {
      news: news.data,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
